package com.kuiya.filter;
import android.os.*;import android.view.*;import android.widget.*;import android.content.res.Configuration;import androidx.appcompat.app.*;import androidx.core.view.*;import com.google.android.material.color.DynamicColors;import com.google.android.material.textfield.TextInputEditText;import com.google.android.material.switchmaterial.SwitchMaterial;import java.util.*;
public class FilterActivity extends AppCompatActivity{
 TextInputEditText words,urls,imageUrls;SwitchMaterial imageWord;android.content.SharedPreferences p;
 public void onCreate(Bundle b){if("system".equals(getSharedPreferences("kuiya",0).getString("theme","kuiya")))DynamicColors.applyToActivityIfAvailable(this);super.onCreate(b);setContentView(R.layout.activity_filter);setupBars(R.id.filterRoot);p=getSharedPreferences("kuiya",0);words=findViewById(R.id.wordsInput);urls=findViewById(R.id.urlsInput);imageUrls=findViewById(R.id.imageUrlsInput);imageWord=findViewById(R.id.imageWordSwitch);words.setText(join(p.getStringSet("words",new LinkedHashSet<>(Arrays.asList("つらい")))));urls.setText(join(p.getStringSet("urls",new LinkedHashSet<>())));imageUrls.setText(join(p.getStringSet("imageUrls",new LinkedHashSet<>())));imageWord.setChecked(p.getBoolean("imageWordEnabled",true));findViewById(R.id.filterToolbar).setOnClickListener(v->finish());findViewById(R.id.saveFilterButton).setOnClickListener(v->save());}
 void save(){p.edit().putStringSet("words",new LinkedHashSet<>(lines(words.getText().toString()))).putStringSet("urls",new LinkedHashSet<>(lines(urls.getText().toString()))).putStringSet("imageUrls",new LinkedHashSet<>(lines(imageUrls.getText().toString()))).putBoolean("imageWordEnabled",imageWord.isChecked()).apply();Toast.makeText(this,"フィルターを保存しました。すぐに適用されます",Toast.LENGTH_SHORT).show();finish();}
 String join(java.util.Set<String>s){return android.text.TextUtils.join("\n",s);}ArrayList<String>lines(String s){ArrayList<String>r=new ArrayList<>();for(String x:s.split("\\n")){x=x.trim();if(!x.isEmpty()&&!r.contains(x))r.add(x);}return r;}
 void setupBars(int id){WindowCompat.setDecorFitsSystemWindows(getWindow(),false);getWindow().setStatusBarColor(android.graphics.Color.TRANSPARENT);getWindow().setNavigationBarColor(android.graphics.Color.TRANSPARENT);boolean light=(getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)!=Configuration.UI_MODE_NIGHT_YES;WindowInsetsControllerCompat c=WindowCompat.getInsetsController(getWindow(),getWindow().getDecorView());c.setAppearanceLightStatusBars(light);c.setAppearanceLightNavigationBars(light);View root=findViewById(id);ViewCompat.setOnApplyWindowInsetsListener(root,(v,in)->{androidx.core.graphics.Insets x=in.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(x.left,x.top,x.right,x.bottom);return in;});ViewCompat.requestApplyInsets(root);}
}
