package com.kuiya.filter;

import android.app.*;import android.os.*;import android.content.*;import android.content.res.Configuration;import android.net.Uri;import android.view.*;import android.view.inputmethod.EditorInfo;import android.webkit.*;import android.widget.*;import androidx.appcompat.app.*;import androidx.core.view.*;import com.google.android.material.color.DynamicColors;import com.google.android.material.dialog.MaterialAlertDialogBuilder;import com.google.android.material.textfield.TextInputEditText;import java.io.*;import java.util.*;import org.json.*;

public class MainActivity extends AppCompatActivity {
 WebView web; TextInputEditText input; View welcome; ArrayList<String> words=new ArrayList<>(),urls=new ArrayList<>(),imageUrls=new ArrayList<>(); android.content.SharedPreferences prefs; String current=""; final int CREATE=10,OPEN=11;
 @Override public void onCreate(Bundle b){applyTheme();super.onCreate(b);setContentView(R.layout.activity_main);setupBars(R.id.mainRoot);prefs=getSharedPreferences("kuiya",0);loadPrefs();web=findViewById(R.id.webView);input=findViewById(R.id.urlInput);welcome=findViewById(R.id.welcome);web.setVisibility(View.GONE);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setBuiltInZoomControls(false);web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){current=u;input.setText(u);if(isBlocked(u)){showBlocked();return;}injectFilter();}});findViewById(R.id.goButton).setOnClickListener(v->go());input.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_GO){go();return true;}return false;});findViewById(R.id.menuButton).setOnClickListener(v->menu());findViewById(R.id.backButton).setOnClickListener(v->{if(web.canGoBack())web.goBack();});findViewById(R.id.forwardButton).setOnClickListener(v->{if(web.canGoForward())web.goForward();});findViewById(R.id.newButton).setOnClickListener(v->{web.stopLoading();web.setVisibility(View.GONE);welcome.setVisibility(View.VISIBLE);input.setText("");});findViewById(R.id.shareButton).setOnClickListener(v->share());handleIntent(getIntent());}
 void applyTheme(){if("system".equals(getSharedPreferences("kuiya",0).getString("theme","kuiya")))DynamicColors.applyToActivityIfAvailable(this);}
 void setupBars(int id){WindowCompat.setDecorFitsSystemWindows(getWindow(),false);getWindow().setStatusBarColor(android.graphics.Color.TRANSPARENT);getWindow().setNavigationBarColor(android.graphics.Color.TRANSPARENT);int mode=getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK;WindowInsetsControllerCompat c=WindowCompat.getInsetsController(getWindow(),getWindow().getDecorView());boolean light=mode!=Configuration.UI_MODE_NIGHT_YES;c.setAppearanceLightStatusBars(light);c.setAppearanceLightNavigationBars(light);View root=findViewById(id);ViewCompat.setOnApplyWindowInsetsListener(root,(v,in)->{androidx.core.graphics.Insets x=in.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(x.left,x.top,x.right,x.bottom);return in;});ViewCompat.requestApplyInsets(root);}
 @Override protected void onResume(){super.onResume();if(prefs!=null){loadPrefs();if(web!=null&&web.getVisibility()==View.VISIBLE)injectFilter();}}
 void handleIntent(Intent i){if(i==null)return;String x=null;try{x=i.getStringExtra(Intent.EXTRA_TEXT);}catch(Exception ignored){}if(x==null&&i.getData()!=null)x=i.getDataString();if(x!=null&&!x.isEmpty()){input.setText(x);new Handler().postDelayed(this::go,300);}}
 void go(){String q=input.getText()==null?"":input.getText().toString().trim();if(q.isEmpty())return;String u=q.matches("^https?://.*")?q:(q.contains(".")&&!q.contains(" ")?"https://"+q:"https://www.google.com/search?q="+Uri.encode(q));if(isBlocked(u)){showBlocked();return;}welcome.setVisibility(View.GONE);web.setVisibility(View.VISIBLE);web.loadUrl(u);}
 boolean isBlocked(String u){for(String x:urls)if(!x.isEmpty()&&!x.contains("<ky>")&&u.toLowerCase().contains(x.toLowerCase()))return true;return false;}
 String quote(String s){return JSONObject.quote(s);}
 String wordRules(){ArrayList<JSONObject>r=new ArrayList<>();for(String x:words){String[]p=x.split("<ky>",2);if(!p[0].trim().isEmpty())try{JSONObject o=new JSONObject();o.put("f",p[0].trim());o.put("r",p.length>1?p[1]:"クイヤ🦫");r.add(o);}catch(Exception ignored){}}Collections.sort(r,(a,b)->Integer.compare(b.optString("f").length(),a.optString("f").length()));return new JSONArray(r).toString();}
 String imageRules(){ArrayList<JSONObject>r=new ArrayList<>();for(String x:imageUrls){String[]p=x.split("<ky>",2);if(!p[0].trim().isEmpty())try{JSONObject o=new JSONObject();o.put("f",p[0].trim());o.put("r",p.length>1?p[1]:"");r.add(o);}catch(Exception ignored){}}return new JSONArray(r).toString();}
 void injectFilter(){boolean imageWordOn=prefs.getBoolean("imageWordEnabled",true);String js="(()=>{const wr="+wordRules()+",ir="+imageRules()+",iwo="+imageWordOn+";const hit=(s,a)=>a.find(x=>x.f&&s.toLowerCase().includes(x.f.toLowerCase()));document.querySelectorAll('img').forEach(i=>{let m=hit(i.src,ir);if(m){if(m.r)i.src=m.r;else{const x=document.createElement('span');x.textContent='🦫';x.style.fontSize='48px';i.replaceWith(x);return}}if(iwo&&hit(i.src,wr)){const x=document.createElement('span');x.textContent='🦫';x.style.fontSize='48px';i.replaceWith(x)}});const walk=n=>{if(n.nodeType===3){let s=n.nodeValue;wr.forEach(x=>{if(x.f)s=s.split(x.f).join(x.r)});n.nodeValue=s}else if(n.nodeType===1&&!['SCRIPT','STYLE','TEXTAREA','INPUT'].includes(n.tagName))n.childNodes.forEach(walk)};if(document.body)walk(document.body)})()";web.evaluateJavascript(js,null);}
 void showBlocked(){welcome.setVisibility(View.GONE);web.setVisibility(View.VISIBLE);String h="<html><body style='font-family:sans-serif;background:#eefbfc;color:#173236;text-align:center;padding:28vh 24px'><div style='font-size:64px'>🦫</div><h1>あんしんクイヤー</h1><h2>このサイトはブロックされました</h2><p>理由 → クイヤ🦫に食べられました。</p></body></html>";web.loadDataWithBaseURL(null,h,"text/html","UTF-8",null);}
 void share(){if(current.isEmpty())return;Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,current);startActivity(Intent.createChooser(i,"リンクを共有"));}
 void menu(){String[]x={"共有","リンクをコピー","設定","クイヤフィルター","KuiyaBackup.jsonを書き出し","KuiyaBackup.jsonを読み込み"};new MaterialAlertDialogBuilder(this).setTitle("クイヤ🦫").setItems(x,(d,w)->{if(w==0)share();else if(w==1){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("URL",current));Toast.makeText(this,"リンクをコピーしました",Toast.LENGTH_SHORT).show();}else if(w==2)startActivity(new Intent(this,SettingsActivity.class));else if(w==3)startActivity(new Intent(this,FilterActivity.class));else if(w==4)exportJson();else importJson();}).show();}
 ArrayList<String>lines(String s){ArrayList<String>r=new ArrayList<>();for(String x:s.split("\\n")){x=x.trim();if(!x.isEmpty()&&!r.contains(x))r.add(x);}return r;}void loadPrefs(){words=new ArrayList<>(prefs.getStringSet("words",new LinkedHashSet<>(Arrays.asList("つらい"))));urls=new ArrayList<>(prefs.getStringSet("urls",new LinkedHashSet<>()));imageUrls=new ArrayList<>(prefs.getStringSet("imageUrls",new LinkedHashSet<>()));}void savePrefs(){prefs.edit().putStringSet("words",new LinkedHashSet<>(words)).putStringSet("urls",new LinkedHashSet<>(urls)).putStringSet("imageUrls",new LinkedHashSet<>(imageUrls)).apply();}
 void exportJson(){try{JSONObject o=new JSONObject();o.put("words",new JSONArray(words));o.put("urls",new JSONArray(urls));o.put("imageUrls",new JSONArray(imageUrls));Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"KuiyaBackup.json");pending=o.toString();startActivityForResult(i,CREATE);}catch(Exception ignored){}}String pending="";void importJson(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,OPEN);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;try{if(r==CREATE){OutputStream o=getContentResolver().openOutputStream(d.getData());o.write(pending.getBytes("UTF-8"));o.close();}else{InputStream in=getContentResolver().openInputStream(d.getData());ByteArrayOutputStream b=new ByteArrayOutputStream();byte[]z=new byte[4096];int n;while((n=in.read(z))>0)b.write(z,0,n);JSONObject o=new JSONObject(b.toString("UTF-8"));words=new ArrayList<>();urls=new ArrayList<>();imageUrls=new ArrayList<>();JSONArray a=o.optJSONArray("words");if(a!=null)for(int j=0;j<a.length();j++)if(!words.contains(a.getString(j)))words.add(a.getString(j));a=o.optJSONArray("urls");if(a!=null)for(int j=0;j<a.length();j++)if(!urls.contains(a.getString(j)))urls.add(a.getString(j));a=o.optJSONArray("imageUrls");if(a!=null)for(int j=0;j<a.length();j++)if(!imageUrls.contains(a.getString(j)))imageUrls.add(a.getString(j));savePrefs();injectFilter();}}catch(Exception e){Toast.makeText(this,"ファイルを処理できませんでした",Toast.LENGTH_SHORT).show();}}
}
